### ISSUE TITLE
Typescript issues

### ISSUE THREAD

**Issue by billnbell** [mmazzarolo/react-native-dialog#102]
Latest version.

Property 'textInputRef' is missing in type '{ value: string | undefined; placeholder: string; onChangeText: (val: string) => void; secureTextEntry: true; }' but required in type 'DialogInputProps'.

It should not be required.

Property 'blurComponentIOS' is missing in type '{ children: Element[]; visible: boolean | undefined; }' but required in type 'DialogContainerProps'.ts(2741)

It should bot be required.

**Comment by mmazzarolo** [comment]
Thanks for reporting. 
Fixed in #103
