### ISSUE TITLE
Backdrop and description enhancements

### ISSUE THREAD

**Issue by devWaleed** [mmazzarolo/react-native-dialog#104]
## Ask your Question

1. How to set opacity of back drop on Android and iOS both, I want to make it more dark as per my theme but I don't see any prop for this? 
2. how to display description below the Input field. I have a scenario in which I have to display some text below Input field as error in red color. I used description but it shows above the Input field not below it.

**Comment by mmazzarolo** [comment]
👋 The goal of this library is to achieve a native look and feel. At the current state, we're not looking into increasing the customization options.

**Comment by mmazzarolo** [comment]
👋 

> How to set opacity of back drop on Android and iOS both

Currently, you can't. 

> I want to make it more dark as per my theme but I don't see any prop for this?

> how to display description below the Input field. I have a scenario in which I have to display some text below Input field as error in red color. I used description but it shows above the Input field not below it.

The goal of this library is to achieve a native look and feel. At the current state, we're not looking into increasing the customization options. 
That said, you can create your own custom text-input by copying/editing [our own Input](https://github.com/mmazzarolo/react-native-dialog/blob/master/src/Input.tsx) component 👍

**Comment by devWaleed** [comment]
Would have never used this component if I knew how mean the author is with closing 100% of the issues in just 10 minutes with no proper answers. Thank you sir.

**Comment by mmazzarolo** [comment]
Sorry, didn't mean to close it, lol

**Comment by devWaleed** [comment]
React Native's alert gives a more darker backdrop and this one has a much lighter backdrop...Now I can't use this plugin because this is different than that.

Further more, by showing description below or above an input field is not going to ruin the native feel.

**Comment by mmazzarolo** [comment]
> React Native's alert gives a more darker backdrop and this one has a much lighter backdrop...Now I can't use this plugin because this is different than that.

Can you provide the backdrop color used by the alert? Instead of making it customizable we should align our [modal's one](https://github.com/mmazzarolo/react-native-dialog/blob/2baf3f18f5a54c57991fd479e9dde3e54b74fe60/src/Modal.tsx#L15-L16) with it. 

> Further more, by showing description below or above an input field is not going to ruin the native feel.

I'd say it depends 🤔 Not 100% against it, but by doing so would introduce a customization option that needs to be designed/maintained. Could you show me an example of how you think it would appear?

**Comment by mmazzarolo** [comment]
Closing, haven't received an answer in > 2 months. Feel free to post here again and I'll re-open the discussion 👍
