### ISSUE TITLE
Warning when using `FormattedMessage` from `react-intl` inside `Dialog.Title`

### ISSUE THREAD

**Issue by SimpleCreations** [mmazzarolo/react-native-dialog#106]
## Environment

Any

## Platforms

Both

## Versions

- react-native-dialog: 8.0.1
- react-native: 0.64.2
- react: 17.0.2

## Description

When using `FormattedMessage` from `react-intl` as `Dialog.Title` children, everything renders as expected, while a warning appears in the console:

```
Warning: Failed prop type: Invalid prop `children` of type `object` supplied to `DialogTitle`, expected `string`.
```

Perhaps `Dialog.Title` (and other components that render only text) should accept arbitrary components as its children, because some of them might be convenience wrappers that render only text.

## Reproducible Demo

```javascript
return (
        <Dialog.Container>
            <Dialog.Title>
                <FormattedMessage
                    id="global.noConnectionDialogTitle"
                    defaultMessage="Connection lost" />
            </Dialog.Title>
        </Dialog.Container>
);
```

**Comment by mmazzarolo** [comment]
Yeah, I think props can be updated 👍 Open to PRs!
