### ISSUE TITLE
Is there a way to disable Light/Dark Mode Support?

### ISSUE THREAD

**Issue by gilhsu** [mmazzarolo/react-native-dialog#107]
## Ask your Question

I'm using Dark Mode on my iPhone but don't want the Dialog container to be dark. Is there a way to disable this?

**Comment by carissacks** [comment]
For the time being, maybe you can set the Dialog styling to match the light mode. Hope it helps

**Comment by ikkyu-3** [comment]
I solved it by adding `UIUserInterfaceStyle` to `info.plist`.

```
<key>UIUserInterfaceStyle</key>
<string>Light</string>
```

https://stackoverflow.com/questions/56537855/is-it-possible-to-opt-out-of-dark-mode-on-ios-13

**Comment by ikkyu-3** [comment]
I solved it by adding `UIUserInterfaceStyle` to `info.plist`.

```
<key>UIUserInterfaceStyle</key>
<string>Light</string>
```

https://stackoverflow.com/questions/56537855/is-it-possible-to-opt-out-of-dark-mode-on-ios-13

**Comment by mmazzarolo** [comment]
Yep, @ikkyu-3's solution is the correct one IMHO (because we're following the native UI guidelines in the component)

**Comment by Slapbox** [comment]
@mmazzarolo is there any plan to allow overriding dark/light modes?

For example, if a user uses an app with dark mode, but at the system level uses light mode, then the dialogs that appear are not themed as the user would prefer/to match the app - and then you have light dialogs over dark screens.

**Comment by rustyonrampage** [comment]
> I solved it by adding `UIUserInterfaceStyle` to `info.plist`.
> 
> ```
> <key>UIUserInterfaceStyle</key>
> <string>Light</string>
> ```
> 
> https://stackoverflow.com/questions/56537855/is-it-possible-to-opt-out-of-dark-mode-on-ios-13

What about android?
