### ISSUE TITLE
Hardware Back Button Handler

### ISSUE THREAD

**Issue by carissacks** [mmazzarolo/react-native-dialog#111]
## Ask your Question

Hi, first of all thank you for creating and maintaining this package. I'm currently using your package and I wonder, is it possible to have a property to handle Hardware Back Button event on Android? Like a callback function to be precise.

Thank you! Much appreciated

**Comment by mmazzarolo** [comment]
Hola! What's stopping you from using https://reactnative.dev/docs/backhandler?

**Comment by carissacks** [comment]
Sorry for the late reply. I tried using back handler in my Alert component which consists of Dialog Elements from your package, but the backAction function is not called. 
I also tried to add the listener on my scene, but the action is handled only when Dialog elements are not visible

**Comment by mmazzarolo** [comment]
> I also tried to add the listener on my scene, but the action is handled only when Dialog elements are not visible

To me, this should be the right approach. You add it to you to your scene, and then in the listener, you check if the modal is open to decide what to do with it 👍

**Comment by carissacks** [comment]
> To me, this should be the right approach. You add it to you to your scene, and then in the listener, you check if the modal is open to decide what to do with it 👍

Thank you for the quick reply. I was just creating my snack in expo. Do you mind taking a look at it [here https://snack.expo.io/@carissa/back-handler](https://snack.expo.io/@carissa/back-handler)?
So when I pressed the hardware back button, it's supposed to call `backAction` function. It works well when dialog is not visible, but it isn't when dialog is visible.

**Comment by mmazzarolo** [comment]
Ah, you're right, it won't be triggered on modals 🤦  
We should add an `onRequestClose` to the container component than to invoke the [modal's `onRequestClose`](https://reactnative.dev/docs/modal#onrequestclose) callback.   
Willing to submit a PR for it? Otherwise, I can look into it when I have some free time.

**Comment by carissacks** [comment]
> Willing to submit a PR for it? Otherwise, I can look into it when I have some free time.

Thanks for checking it out. I'll try creating one by the end of the week 🙆‍♀️
