### ISSUE TITLE
iOS - Load multiple Dialogs at the same time. 

### ISSUE THREAD

**Issue by josejhj2** [mmazzarolo/react-native-dialog#116]
Is it possible to display 2 Dialogs at the same time? ie. One on top of the other? This is working for Android but not iOS. 
Example: I'm displaying a Yes/No dialog, but after inactivity I need to show a new dialog on top. When the top dialog is close, the bottom Yes/No dialog should still be there.

**Comment by mmazzarolo** [comment]
Hi! Nope, it's not possible with the current implementation of React-Native's own Modal component.
