### ISSUE TITLE
Doesn't work with modals

### ISSUE THREAD

**Issue by mstfymrtc** [mmazzarolo/react-native-dialog#13]
I've been trying to use react-native-dialog, also I use native Modal. But if I pass visible={this.state.isDialogVisible} prop to dialog container, it does not trigger set state method which is this.setState({isDialogVisible:true})
But if I directly pass visible={true} prop to dialog, it remains visible.

**Comment by mmazzarolo** [comment]
Could you please provide an example?

**Comment by mstfymrtc** [comment]
I've found workaround, actually this problem wasn't about react-native-dialog. If there is a situation which requires using multiple modals, second modal needs to be nested inside first modal. Thanks for this great component!
