### ISSUE TITLE
Screen orientation forcibly changed to potrait from landscape in iOS when dialog is shown

### ISSUE THREAD

**Issue by Corliansa** [mmazzarolo/react-native-dialog#130]
## Environment
System:
    OS: macOS 12.0.1
    CPU: (8) x64 Apple M1
    Memory: 25.65 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 6.14.12 - /usr/local/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: javac 16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.3 => 0.64.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

## Platforms
iOS

## Versions

- react-native-dialog: "^9.2.0",
- react-native: "0.64.3",
- react: "17.0.1",

## Description

When the dialog is shown, the screen orientation is forcibly changed to potrait ( i am using "orientation": "landscape" ). This only affects iOS.

## Reproducible Demo
```javascript
import React, { useState } from "react";
import { Button, StyleSheet, View } from "react-native";
import Dialog from "react-native-dialog";
import { DrawerItem } from "@react-navigation/drawer";

export default function DialogModal(props: any) {
	const [visible, setVisible] = useState(props.visible);
	const [text, setText] = useState("");
	const navigation = props.navigation;

	const showDialog = () => {
		setVisible(true);
	};

	const handleCancel = () => {
		setVisible(false);
	};

	const handleSearch = () => {
		// The user has pressed the "Delete" button, so here you can do your own logic.
		// ...Your logic
		setVisible(false);
	};

	return (
			<View style={styles.container}>
                                 <Button title="Show dialog" onPress={showDialog} />
				<Dialog.Container visible={visible}>
					<Dialog.Title>Search</Dialog.Title>
					<Dialog.Description>Search something...</Dialog.Description>
					<Dialog.Input
						onChangeText={(e: any) => setText(e)}
						onSubmitEditing={handleSearch}
						autoCorrect={false}
						autoCapitalize="none"
					/>
					<Dialog.Button label="Cancel" onPress={handleCancel} />
					<Dialog.Button label="Search" onPress={handleSearch} />
				</Dialog.Container>
			</View>
	);
}

const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "#fff",
		alignItems: "center",
		justifyContent: "center",
	},
});
```

**Comment by jacobpenny** [comment]
You can use https://reactnative.dev/docs/modal#supportedorientations-ios here since `Dialog.Container` will pass it through.
```js
    <DialogContainer
      supportedOrientations={['portrait', 'landscape']}
    >
```
