### ISSUE TITLE
Dialog.Description text seems to use incorrect color in iOS

### ISSUE THREAD

**Issue by Calinteodor** [mmazzarolo/react-native-dialog#132]
Hey all! 

I am developer from the Jitsi Meet team, an open source project that helps with instant video conferences. 
Let me first say that your components gave a fresh breath of air to our internal dialogs, that, right now, look and feel more native than ever! Also, the documentation was really easy to follow. 

While implementing, I noticed a slight difference between the dialog description text color from your screenshots and the one from mine 

![image](https://user-images.githubusercontent.com/26413496/153018491-2caadd32-43e6-4ec4-9cfd-cd233269706f.png)

As you can see, in light mode, the text visibility is low.
From your screenshot the text color, PlatformColor("label"), is the same for every dialog component, but if you go to Description.tsx you'll see that PlatformColor("secondaryLabel") is used. 

Is this intended? If not I can help and create a PR with this small fix.

All the best!

**Comment by mmazzarolo** [comment]
Hey @Calinteodor ! Yeah, it's probably a mistake :) 
If you could test the fix and submit a PR, that would be great, thanks!

**Comment by mmazzarolo** [comment]
Fixed in #133
