### ISSUE TITLE
Support statusBarTranslucent

### ISSUE THREAD

**Issue by jzxchiang1** [mmazzarolo/react-native-dialog#137]
Just need to add `statusBarTranslucent` as a configurable prop here:

https://github.com/mmazzarolo/react-native-dialog/blob/dd6d979279b22ad869d95ba530a1e9cd1fc1601b/src/Modal.tsx#L191

Otherwise, Android apps will look a little strange if their status bar is indeed translucent...

**Comment by Slapbox** [comment]
@jzxchiang1 try passing `transparent={false}` to `Dialog.Container`. Unless I'm reading the code wrong, that should get applied like you want.

**Comment by Slapbox** [comment]
It works for us. I believe this can be closed.

**Comment by mmazzarolo** [comment]
Yup. Thanks @Slapbox !
