### ISSUE TITLE
onBackdropPress is not working

### ISSUE THREAD

**Issue by theapache64** [mmazzarolo/react-native-dialog#14]

**Comment by mmazzarolo** [comment]
This feature is not available right now. 
If you want you can expose this feature from `onBackdropPress` from `react-native-modal`.

**Comment by theapache64** [comment]
and how do i do that ? could you please be more specific ?

**Comment by mmazzarolo** [comment]
Unfortunately I can't test it at the moment.
 
Seems weird 🤔 , you can see at [this line](https://github.com/mmazzarolo/react-native-dialog/blob/62b722a71c7dbb57ce627b1fa53217a22e41430d/src/Container.js#L62) that Dialog.Container accepts and spreads all the modal props.

**Comment by theapache64** [comment]
Yeah, I saw that. but it's not working unfortunately. :/

**Comment by mmazzarolo** [comment]
Re-opening 👍

**Comment by mmazzarolo** [comment]
I think what is causing this behaviour is the blur overlay swallowing the inputs.

**Comment by servocoder** [comment]
Not working as well. Any update?

**Comment by servocoder** [comment]
I found the root of the issue. You have to remove `flex` styling from [this line](https://github.com/mmazzarolo/react-native-dialog/blob/master/src/Container.js#L100). So the final `container` styling should looks like:

```
  container: {
    justifyContent: "center",
    alignItems: "center"
  },
```

This fix deserves a new release ;)

**Comment by servocoder** [comment]
Any chance to get this fix included into the next release?

**Comment by mmazzarolo** [comment]
Does the backdrop show up normally with the change? Would you submit a PR? Thanks!

**Comment by gianpaj** [comment]
Thanks for the fix @fjmorant 👏 

The PR https://github.com/mmazzarolo/react-native-dialog/pull/26 is waiting to be merged. I've tested it by changing the `Container.js` file manually from the `node_modules` folder.
