### ISSUE TITLE
Needs to be upgraded to use deprecated-react-native-prop-types

### ISSUE THREAD

**Issue by Slapbox** [mmazzarolo/react-native-dialog#146]
0.69 breaks this library.

PS @mmazzarolo I didn't forget about the other incomplete PRs I still owe you!

**Comment by Slapbox** [comment]
Listing specific changes needed:

- Import `ViewPropTypes` `deprecated-react-native-prop-types` instead of `react-native`
-  `style: (Text as any).propTypes.style` - Unknown how to update this properly

**Comment by mmazzarolo** [comment]
Hello hello @Slapbox ! 
I'm also not familiar with any new React-Native-specific prop (nor with newer React-Native versions in general 😓). 
I'm fine with any approach that solves the current incompatibility, even if it means making the prop typing more flexible — we can then create follow-up GitHub issues about known potential improvements. 
Thank you!

**Comment by Slapbox** [comment]
Obsolete before I even made the issue! Fixed by #139.
