### ISSUE TITLE
Allow to change fade time when dialog container is closed

### ISSUE THREAD

**Issue by Brenosalv** [mmazzarolo/react-native-dialog#148]
## New prop request

The fade time when dialos container is closed is slow. I would like to change this time but apparently there is no prop for it.

**Comment by mmazzarolo** [comment]
👋 Hey! The goal of this library is to achieve a native look and feeling. At the current state we're not looking into increasing the customization options. If you think the fade timing doesn't match the native counterpart, feel free to submit a new PR. Thanks!
