### ISSUE TITLE
Setting opacity to "100%"?

### ISSUE THREAD

**Issue by mstfymrtc** [mmazzarolo/react-native-dialog#16]
Hello, Is there any way to set opacity "100%" for Dialog.Container?

**Comment by mmazzarolo** [comment]
Yes, you can pass `backdropOpacity={1}` to the `Dialog.Container`.

(It's not documented  since it's an internal `react-native-modal` prop).

**Comment by mstfymrtc** [comment]
<img width="321" alt="screen shot 2018-09-03 at 10 26 59" src="https://user-images.githubusercontent.com/5208454/44973060-f4e3e800-af63-11e8-856a-305c82d3e3ea.png">
setting  backdropOpacity={1} causes black backround.
