### ISSUE TITLE
the dialog is transparent.

### ISSUE THREAD

**Issue by intergalactic-overlords** [mmazzarolo/react-native-dialog#22]
The dialog is transparent (and the native one is not...), which looks very messy. There should at least be an option to turn the transparency off.
![simulator screen shot - iphone xr - 2018-10-01 at 15 30 56](https://user-images.githubusercontent.com/2363710/46291660-59a85780-c58f-11e8-8589-814956e085b8.png)
![simulator screen shot - iphone xr - 2018-10-01 at 15 30 02](https://user-images.githubusercontent.com/2363710/46291661-59a85780-c58f-11e8-831d-c390420a5db3.png)

**Comment by mmazzarolo** [comment]
Please see the last comment in PR #21 
Could you give it a test so that than I can submit a new release on npm?

**Comment by indapublic** [comment]
@mmazzarolo Confirmed.

Previous:
![screen shot 2018-10-03 at 17 57 21](https://user-images.githubusercontent.com/856260/46397558-dc6b1700-c735-11e8-9141-0794d4049bdd.png)

With your latest changes:
![screen shot 2018-10-03 at 17 56 50](https://user-images.githubusercontent.com/856260/46397569-e1c86180-c735-11e8-9fda-6ebf815ba4d0.png)

**Comment by intergalactic-overlords** [comment]
@mmazzarolo I have tested and can confirm it works. Great job guys.

**Comment by mmazzarolo** [comment]
Thanks @indapublic and @intergalactic-overlords , publishing on npm right now :)

**Comment by mmazzarolo** [comment]
Landed on [v5.4.0](https://github.com/mmazzarolo/react-native-dialog/releases/tag/v5.4.0)
