### ISSUE TITLE
TextInput label style mistakes

### ISSUE THREAD

**Issue by TimurAsayonok** [mmazzarolo/react-native-dialog#23]
I have played with your lib during my free time for watching what we can use for our application, and I have found small style mistake with label into TextInput component.

So, problem is that you put `Text` component with `label` into `View` with `textInputWrapper` styles that means that label will be shown inside text input - like on images (iOS):
![screen shot 2018-10-02 at 20 05 35](https://user-images.githubusercontent.com/17002747/46369050-0fec6980-c682-11e8-8aac-8650570d25e6.png)
on Android all is ok, but we don't have bottom border for textInput

I suggest to create new View which will wrappe lable Text component and View with TextInput, and move part of styles from `<View style={styles.textInputWrapper}>...</View>` to `<View style={styles.container}>...</View>` and code will be like this:

```
<View style={styles.container}>
    {label && <Text style={styles.label}>{label}</Text>}
    <View style={[styles.textInputWrapper, wrapperStyle]}>
        <TextInput
          ref={textInputRef}
          style={[styles.textInput, style, { height }]}
          multiline={multiline}
          numberOfLines={numberOfLines}
          {...otherProps}
        />
    </View>
</View>
```
and styles will be:
```
container: Platform.select({
    ios: {
      marginHorizontal: 20,
      marginBottom: 20
    },
    android: {
      marginHorizontal: 10,
      marginBottom: 20
    }
  }),
textInputWrapper: Platform.select({
  ios: {
    backgroundColor: "white",
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 6,
    paddingHorizontal: 8,
    borderColor: "#A9ADAE",
  },
  android: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#A9ADAE",
  }
}),
```

and we will get (ios and android):
![screen shot 2018-10-02 at 20 08 30](https://user-images.githubusercontent.com/17002747/46369508-82aa1480-c683-11e8-909f-ca80bb06e39d.png)
![screen shot 2018-10-02 at 20 50 48](https://user-images.githubusercontent.com/17002747/46370067-f13ba200-c684-11e8-8c78-965a9ab3c510.png)

**Comment by mmazzarolo** [comment]
Hey @TimurAsayonok ! Thanks for starting a discussion :)
One question: why do you want to supply the label to iOS?
Following the design guidelines of both alert I think that we should use the placeholder on iOS and the label on Android... am I wrong? 🤔

**Comment by TimurAsayonok** [comment]
Hey @mmazzarolo, I don't use label to iOS in my project =), I just have checked props which you mention in readme. And I think that if you want to use label only for android you should add text that this props only for android) Because if we use label as placeholder for iOS it will be wrong and we will get result as I have sent. Because for placeholder we can use placeholder props in default TextInput props.
And If we use label only for android we should have border styles =)

Best regards

**Comment by mmazzarolo** [comment]
@TimurAsayonok I agree, that's my fault. 
I haven't worked a lot on this library after its first release (it's being used in two production apps I developed long time ago) so suggestions are more than welcome.  
Since I'd like to match as close as possible the iOS/Android dialog design guidelines, should we just disable the `label` when on iOS (in the `DialogInput`)? What do you think?

**Comment by TimurAsayonok** [comment]
I tried to find information about `label` for text input in the iOS design guidelines (alert and text field) and didn't find anything about it =)

I think if we disable `lable` for iOS and update the README, it will be ok
