### ISSUE TITLE
Calling TextInput methods?

### ISSUE THREAD

**Issue by mateusz-** [mmazzarolo/react-native-dialog#27]
Hi,

How can I call TextInput methods (blur / focus / update) using Dialog.Input references? Not possible currently, correct?

In my case, I am trying to call focus() from another input element:
```js
<Dialog.Input
  onSubmitEditing={() => this.routerPskInput.focus()}
  blurOnSubmit={false}
  ref={input => this.routerIdentityInput = input}
/>
<Dialog.Input
  ref={input => this.routerPskInput = input}
/>
```

**Comment by mateusz-** [comment]
The solution is to use textInputRef property.

Doesn't seem to be documented in the README.md at this moment.

**Comment by forki** [comment]
please reopen - this should be documented

**Comment by mmazzarolo** [comment]
> please reopen - this should be documented

@forki I'm open to PRs 👍
