### ISSUE TITLE
How do I auto focus on TextInput when open?

### ISSUE THREAD

**Issue by hteiktinoo** [mmazzarolo/react-native-dialog#29]
textInputRef={ i => this.input = i  }
will give me undefined

**Comment by mmazzarolo** [comment]
https://github.com/mmazzarolo/react-native-dialog/issues/27

I know, I have to work on the docs :/ I don't have any free time for that though...

**Comment by mmazzarolo** [comment]
Wait, do you mean that adding the `textInputRef` to the DialogTextInput component didn't work?

**Comment by hteiktinoo** [comment]
You’re right. Using my code above, I couldn’t set this.input.focus() in a button onClick

**Comment by mmazzarolo** [comment]
could you please share the entire snipper/code?

**Comment by hteiktinoo** [comment]
Here're it is

`onAdd = () => {`
`this.setState({ modalOpen: true })`
**`console.log(this.input) // undefined`**
**`this.input.focus() // not working`**
`}`
`render(){`
`return(`
`<View>`
`<TouchableOpacity onPress={this.onAdd} >`
`<Text>Add New Text</Text>`
`</TouchableOpacity>`
`<Dialog.Container visible={modalOpen}>`
  `          <Dialog.Title>Title</Dialog.Title>`
   `         <Dialog.Input value={text} textInputRef={i=>this.input=i} onChangeText={i => this.setState({ text: i })} ></Dialog.Input>`
`            <Dialog.Button label="Cancel" onPress={()=>this.setState({ modalOpen: false })} />`
 `           <Dialog.Button label="Add"  />`
  `       </Dialog.Container>`
`</View>`
`)`
`}`

**Comment by hteiktinoo** [comment]
autoFocus={true} works perfectly. Thanks!
