### ISSUE TITLE
Way too long delay to show/hide?

### ISSUE THREAD

**Issue by emmx** [mmazzarolo/react-native-dialog#30]
Is it only on my phone or it does take long (~2 seconds) to show and hide?

I was expecting it to behave pretty much like ReactNative's Alert in terms of performance but with this delay I can't use it. Any workaround or way to improve it?

**Comment by mmazzarolo** [comment]
Hey! It shouldn’t have any lag. 
Try playing around with it with a minimal example (like in the one from the README) and I’d the issue persist could you open a new issue report (by making sure follow to the template)?

**Comment by tmikeschu** [comment]
@emmx did you find a solution? I am experiencing the same behavior, even with the most basic example from the docs.

**Comment by BaderSerhan** [comment]
Me too.
