### ISSUE TITLE
Flashing on exit

### ISSUE THREAD

**Issue by philipaarseth** [mmazzarolo/react-native-dialog#32]
Hi,

When I dismiss the dialog the dark background low opacity layer flashes quickly twice before disappearing.
Has anyone noticed this?

**Comment by mmazzarolo** [comment]
🤔 any additional info/video? what device are you using? are you in development mode? release?

**Comment by philipaarseth** [comment]
![screen recording 2019-01-24 at 14 42 23](https://user-images.githubusercontent.com/31098164/51681981-8670f680-1fe6-11e9-9d45-ecfe67b88b45.gif)
iOS simulator on MacOS. in dev mode. 
"react-native": "0.57.8",
"react-native-dialog": "^5.5.0",

**Comment by mmazzarolo** [comment]
That's weird, it shouldn't happen 🤔 
Are you updating the state in the callback? 
Also, could you check if just using the "Complete example" in the README.md still do the same flashing?

**Comment by mmazzarolo** [comment]
will check

**Comment by philipaarseth** [comment]
Did you figure it out @mmazzarolo ?

**Comment by mmazzarolo** [comment]
Nope, sorry, haven't had a chance to check yet :/ pretty busy these weeks

**Comment by LondonJammo** [comment]
Same for me

**Comment by mmazzarolo** [comment]
I can reproduce it. Checking.

**Comment by mmazzarolo** [comment]
@LondonJammo @philipaarseth could you try setting the `useNativeDriver` prop to `true` in `Dialog.Container`? 
Seems to solve the issue for me:


```js
render() {
    return (
      <View
        style={{ flex: 1, backgroundColor: "blue", justifyContent: "center" }}
      >
        <TouchableOpacity onPress={this.showDialog}>
          <Text>Show Dialog</Text>
        </TouchableOpacity>
        <Dialog.Container
          visible={this.state.dialogVisible}
          useNativeDriver={true}
        >
          <Dialog.Title>Account delete</Dialog.Title>
          <Dialog.Description>
            Do you want to delete this account? You cannot undo this action.
          </Dialog.Description>
          <Dialog.Button label="Cancel" onPress={this.handleCancel} />
          <Dialog.Button label="Delete" onPress={this.handleDelete} />
        </Dialog.Container>
      </View>
    );
  }
```

**Comment by LondonJammo** [comment]
> ```js
> useNativeDriver={true}
> ```

This solves the flicker/flash. There is still a small cosmetic issue though:
On closing: 
- the dialog content fades away
- the dialog border remains briefly, and then fades away.
- this shows a hollow transparent box over the underlying content.

**Comment by mmazzarolo** [comment]
Mind showing a video/GIF?

**Comment by admiralicic** [comment]
Hi, has anybody found a solution to the above issue described by @LondonJammo ?

**Comment by juniorlp123** [comment]
> > ```js
> > useNativeDriver={true}
> > ```
> 
> This solves the flicker/flash. There is still a small cosmetic issue though:
> On closing:
> 
> * the dialog content fades away
> * the dialog border remains briefly, and then fades away.
> * this shows a hollow transparent box over the underlying content.

Any update on this? Same is happening to me

**Comment by juniorlp123** [comment]
I've found the solution! Just add `renderToHardwareTextureAndroid={true}` to `<AnimatedModal/>` in Container.js
