### ISSUE TITLE
Dialog variables in Description

### ISSUE THREAD

**Issue by LondonJammo** [mmazzarolo/react-native-dialog#34]
Per docs, you use static text inside the elements:

```
<Dialog.Description>
            Do you want to delete this account? You cannot undo this action.
</Dialog.Description>
```

However, if I want to change this text by setting it later, I use a variable:

`<Dialog.Description> { this.description } </Dialog.Description>`

The value changes correctly, but but I get a warning in the emulator:

`Warning: Failed prop type: Invalid prop 'children' of type 'array' supplied to 'DialogDescription', expected 'string'`

**Comment by mmazzarolo** [comment]
@LondonJammo could you share your code?
Are you sure you're not supplying an array instead of the description? (e.g.: by doing a check like `this.list && this.description`?)

This is working fine for me:

```js
render() {
    const description = `Do you want to delete this account? You cannot undo this action.`;
    return (
      <View
        style={{ flex: 1, backgroundColor: "blue", justifyContent: "center" }}
      >
        <TouchableOpacity onPress={this.showDialog}>
          <Text>Show Dialog</Text>
        </TouchableOpacity>
        <Dialog.Container visible={this.state.dialogVisible}>
          <Dialog.Title>Account delete</Dialog.Title>
          <Dialog.Description>{description}</Dialog.Description>
          <Dialog.Button label="Cancel" onPress={this.handleCancel} />
          <Dialog.Button label="Delete" onPress={this.handleDelete} />
        </Dialog.Container>
      </View>
    );
  }
```

**Comment by LondonJammo** [comment]
Thanks for your reply. The issue seems to have fixed itself as the message no longer appears. Not sure what caused it, as I can't replicate the error anymore.

**Comment by cbril** [comment]
I experienced the same issue.

This gives the warning:
`<Dialog.Description>Are you sure you want to delete {item}?</Dialog.Description>`

Removed the warning by doing this:
```
let description = `Are you sure you want to delete {item}?`;
...
<Dialog.Description>{description}</Dialog.Description>
```

LondonJammo probably removed the spaces surrounding the curly braces. It would be nice to have a fix for this.

**Comment by mmazzarolo** [comment]
@cbril it's probably an issue with the variable interpolation when passed down to a child. 
Since moving it into a variable seems to fix the issue I think adding this bit in the README.md could be enough. 
Open to PR
