### ISSUE TITLE
Dialog.input value="ABC" locks the field

### ISSUE THREAD

**Issue by LondonJammo** [mmazzarolo/react-native-dialog#36]
Dialog.input, when using Label="ABC" this adds an extra text field which acts as a heading/title for the input.

These days in UX, users are more used to the input field itself being prefilled with a value which acts like a title, such as Name or Email

When setting dialog.input value="ABC" this does just that. However, it also locks the field making it impossible to change its value.

**Comment by mmazzarolo** [comment]
@LondonJammo Not sure I'm following you. 

> These days in UX, users are more used to the input field itself being prefilled with a value which acts like a title, such as Name or Email

`Dialog.Input` is just a RN Input, so you can simply use the `placeholder` field for that. 

 > When setting dialog.input value="ABC" this does just that. However, it also locks the field making it impossible to change its value.

That's the correct behaviour: `Dialog.Input` is a controlled component (like the RN Input) so you'll be responsible of keeping the input value in the state. 

Let me know if I'm missing anything! 👍
