### ISSUE TITLE
Dialogue Buttons are covered by Keyboard

### ISSUE THREAD

**Issue by naytun** [mmazzarolo/react-native-dialog#38]
Hi @mmazzarolo, I like the versatility of  your component! There's one minor UX issue. Can we position the dialogue box so that the buttons are not covered by keyboard? Thanks.

![simulator screen shot - iphone x - 2019-03-04 at 16 48 56](https://user-images.githubusercontent.com/10265410/53765293-990c0480-3e9d-11e9-9d83-25f8b765bc69.png)

**Comment by naytun** [comment]
I found a way to do that, in case somebody have the same issue.
```
<Dialog.Container
            contentStyle={{ marginBottom: 45 }}
>
```

**Comment by mmazzarolo** [comment]
Also setting `avoidKeyboard={true}` in the `Dialog.Container` should work.  
`avoidKeyboard` is a [react-native-modal](https://github.com/react-native-community/react-native-modal) prop.  
Glad you fixed it btw :)

**Comment by ShivamJoker** [comment]
> Also setting `avoidKeyboard={true}` in the `Dialog.Container` should work.
> `avoidKeyboard` is a [react-native-modal](https://github.com/react-native-community/react-native-modal) prop.
> Glad you fixed it btw :)

It doesn't seem to be working as of now. Can you please take a look ?
