### ISSUE TITLE
Version not published

### ISSUE THREAD

**Issue by diego-antonelli** [mmazzarolo/react-native-dialog#41]
PR was merged (https://github.com/mmazzarolo/react-native-dialog/pull/40) but not published in NPM. Please publish as soon as you can :)

**Comment by mmazzarolo** [comment]
I won't be available to publish it until this weekend, could you use the `master` branch in your package in the meanwhile?

**Comment by diego-antonelli** [comment]
No problem, thanks a lot for your attention

**Comment by mmazzarolo** [comment]
@diego-antonelli published in [`v5.6.0`](https://github.com/mmazzarolo/react-native-dialog/releases/tag/v5.6.0)
