### ISSUE TITLE
QUESTION: How does dialog.input work ?

### ISSUE THREAD

**Issue by AlexMachin1997** [mmazzarolo/react-native-dialog#46]
Hi,

I'm very interested in your library for a popup modal which accepts inputs and dialogue messages.

However, I'm a little confused about the input. How exactly would it work? Could you provide a small example?

Cheers,
Alex

**Comment by mmazzarolo** [comment]
Hey @AlexMachin1997 , you're right, the docs are not good 😞 
The `Dialog.Input` component accepts all the  React-Native's `TextInput` component props, so you can use it just like a standard TextInput (by keeping its text in the state).

**Comment by AlexMachin1997** [comment]
Ah ok.

So when using Dialog.Input it renders an input, you would just need to mention that Dialog.Input inherits all the props from TextInput.

Thanks for answering my question quickly :)

**Comment by mmazzarolo** [comment]
Yup, done :)
