### ISSUE TITLE
How to get Dialog.Input value?

### ISSUE THREAD

**Issue by ivanharsono** [mmazzarolo/react-native-dialog#5]

**Comment by mmazzarolo** [comment]
Hey!
The `Dialog.Input` accepts all the [React-Native's TextInput](https://facebook.github.io/react-native/docs/textinput.html) props.

**Comment by franck-nadeau** [comment]
In other words, something like this will work.      

       <Dialog.Input
          onChangeText={text => this.setState({ text })}
        />

**Comment by forki** [comment]
please document in readme

**Comment by mmazzarolo** [comment]
> please document in readme
I'm open to PRs 👍
