### ISSUE TITLE
[Android] Dialog hides system bar

### ISSUE THREAD

**Issue by dykra** [mmazzarolo/react-native-dialog#53]
After rendering dialog, system bar is hidden with the white background.

![Screenshot 2019-07-11 at 09 29 45](https://user-images.githubusercontent.com/23487423/61031840-93c94400-a3c0-11e9-9ad2-67e6fe69e897.png)

While the time and notifications should be visible like with the use of system alert:
![Screenshot 2019-07-11 at 10 04 36](https://user-images.githubusercontent.com/23487423/61033238-54502700-a3c3-11e9-9faf-b77d33a49e15.png)

**Comment by mmazzarolo** [comment]
👋 Unfortunately this is a React-Native issue with its internal Modal, more info [here](https://github.com/react-native-community/react-native-modal#the-statusbar-style-changes-when-the-modal-shows-up)
