### ISSUE TITLE
change font color inside button when `disabled` props is set

### ISSUE THREAD

**Issue by achmadk** [mmazzarolo/react-native-dialog#7]
Hello @mmazzarolo , I am using this library to create my company app. This library is good to use, but I have several problem when using your library. The other one is font color inside `Dialog.Button` still same as default when `disabled` props is set. Although that button is non-clickable, maybe the users perceive that button is clickable. I hope this problem has solved quickly and other developers use this library for their hybrid mobile app.

**Comment by mmazzarolo** [comment]
Hey @achmadk !
You can fix it easily by passing your own color when the button is disabled 👍
