### ISSUE TITLE
Can't Open a Dialog after immediately close previous one

### ISSUE THREAD

**Issue by AmirF194** [mmazzarolo/react-native-dialog#70]
I created a dialog with Dialog.Input Using setstate to get a password from user. if the password  was correct the first dialog should close, then another one which also has a Dialog.Input should appear.( by updating state values false/true).
Everything on android works like a charm but on ios i got this warning : 
Warning: Attempt to present <RCTModalHostViewController: 0x....> on <UIViewController: 0x....> which is already presenting <RCTModalHostViewController: 0x....>
The first dialog disappears but the second one never appears. 
What should I do ?

**Comment by RRMoelker** [comment]
Same problem here on iOS.

I managed to work around it by setting the visibility of second modal using `onModalHide` on the first modal.

So something like:

```typescript
enum Step {
  Idle,
  Modal1,
  HidingModal1,
  Modal2,
}

...

const changeToModal2 = () => {
  setStep(Step.HidingModal1);
}

...

<Dialog.Container
  visible={showModal1}
  onModalHide={() => setStep(Step.Modal2)}
>
  ...
</Dialog.Container>
<Dialog.Container
  visible={showModal2}
>
  ...
</Dialog.Container>
```

**Comment by mmazzarolo** [comment]
👋 I'm closing this issue because I just did a complete refactoring of `react-native-dialog`. 
FYI, @RRMoelker you solution is the correct one. `onModalHide` is not `onHide`.
