### ISSUE TITLE
check refactor for any objections

### ISSUE THREAD

**Issue by tyxou** [mmazzarolo/react-native-dialog#72]
First, thanks for a great module! 
Due to the upcoming deprecation of the `class` component I decided to refactor into functions / Hooks.
Considering the positive updates in `Modal` within `react-native` I decided to remove `react-native-modal` and use the native one instead.
Whenever convenient, please check the below repo for any objections (possibly within the markdown file) and I would be happy to amend as needed:
https://github.com/tyxou/react-native-dialog

Thanks once again!

**Comment by mmazzarolo** [comment]
I can't try it now but code looks good to me 👍 (and I also like the modal change)
If you want to submit a PR as it is I can test it in the weekend.

**Comment by mmazzarolo** [comment]
(and thanks!)

**Comment by mmazzarolo** [comment]
Closing as per #73 . FYI I added a thank you not for you at the bottom of the README.md 👍
