### ISSUE TITLE
Add TypeScript type definitions

### ISSUE THREAD

**Issue by mmazzarolo** [mmazzarolo/react-native-dialog#75]

**Comment by ShivamJoker** [comment]
will definitely try to add cause not getting any autocomplete

**Comment by mmazzarolo** [comment]
I think supporting these https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native-dialog/index.d.ts could be a good starting point

**Comment by warrenseine** [comment]
I've added Switch to the typings: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50830
