### ISSUE TITLE
Dark-mode support

### ISSUE THREAD

**Issue by mmazzarolo** [mmazzarolo/react-native-dialog#76]
- Abstract the style colors into light/dark mode
- Pick the right style colors based on the currently selected mode

**Comment by Thitiwut** [comment]
I will work on this issue.
Could you add hacktoberfest tag on this I will working on your issue.  👍

**Comment by Prozhou** [comment]
Watch on this feature.

**Comment by dapicester** [comment]
Have a look at the [`PlatformColor` API](https://reactnative.dev/docs/platformcolor), I think the library should use those colors instead of hardcoding black and white.

**Comment by nephix** [comment]
Also looking forward to this

**Comment by CodingByJerez** [comment]
@dapicester 
#100
