### ISSUE TITLE
Way to make keyboard dismiss on button press

### ISSUE THREAD

**Issue by zzorba** [mmazzarolo/react-native-dialog#9]
First of all love the library.  I'm having trouble on IOS where the buttons require two taps to click on when using a TextInput.  First tap dismisses the keyboard, the second one actually registers to the button.

It seems like there are ways to add properties to containing Views to make this not happen, but it doesn't look like there's a way to inject props into the `View` that wraps buttons in this library.

Any advice for getting around this issue?

**Comment by mmazzarolo** [comment]
Hey! Do you mind submitting a PR? :) Let me know if I can help with that

**Comment by zzorba** [comment]
Will do!

**Comment by zzorba** [comment]
I don't know what happened, but I can't seem to reproduce the problem anymore.  If it comes up again will try to fix it in a forked library and submit a PR.

**Comment by sniperosx** [comment]
Hello, 
same problem here in 2021. Still having the problem (iOS & Android) that a touch of any button is first dismissing the keyboard and another click is getting to the buttons. Seems that the keyboard dismissal view is laying on top of the complete dialog. 

@zzorba Did you find a workaround for this?

**Comment by FrancescoBonizzi** [comment]
Same problem here in 2022

**Comment by ColeTownsend** [comment]
Same thing here, I might code in a keyboard listener. Hacky but its the only idea I have.

**Comment by jordansoltman** [comment]
2023 checking in with the same problem!

**Comment by jordansoltman** [comment]
Found the solution! 

In my case, it had nothing to do with `react-native-dialog`. It has to do with TextInput behavior within a ScrollView. My dialog was technically inside of a ScrollView, so setting `keyboardShouldPersistTaps` to `handled` on **the ScrollView** now allows for the buttons to be pressed without requiring the two taps! Hope this helps you in 2024 😉
