### ISSUE TITLE
Support of avoidKeyboard?

### ISSUE THREAD

**Issue by blueberry6401** [mmazzarolo/react-native-dialog#91]
## Ask your Question

As the removing of react-native-modal, the avoidKeyboard not working anymore. Is there any plan to make this works again?

**Comment by mmazzarolo** [comment]
Isn't https://github.com/mmazzarolo/react-native-dialog/pull/93 fixing your issue? 
We do support KeyboardAvoidView... if it doesn't work, there might be a bug :)

**Comment by lightningmce** [comment]
Does it have a solution for Android?

**Comment by exotexot** [comment]
Why is this even optional?
Shouldn't this be a default behaviour to use a KeyboardAvoidingView, which would work cross platform.

**Comment by mmazzarolo** [comment]
I think #93 solved this issue. If it hasn't please feel free to submit a new issue (with more details on how to reproduce it, on which platform, and with a minimal reproducible example -- thanks!)
