### ISSUE TITLE
Please add prop to disable animation

### ISSUE THREAD

**Issue by exotexot** [mmazzarolo/react-native-dialog#94]
I like the component. But don't like its animation behaviour. It would be nice to pass an animationConfig prop to the component, allowing for the option to completely disable it.

**Comment by mmazzarolo** [comment]
Hi Exotexot! The goal of this library is to achieve a native look and feel. 
At the current state, we're not looking into increasing the customization options — but if you think the new animation would look more "native", feel free to send a pull-request!
