### ISSUE TITLE
Background Color don't change on IOS

### ISSUE THREAD

**Issue by rastilho8** [mmazzarolo/react-native-dialog#96]
## Background Color problem

I changed the background color of my dialog using contentStyle as it says in the docs. However, on android the color applies, but on iOS it doesn't. I'm doing something wrong or is it a library problem?

The code I am using is 
`contentStyle={{backgroundColor: '#xxx'}}`

**Comment by tolik85** [comment]
@rastilho8 did you find a solution? Same issue on my side.

**Comment by AlexandreMouyen** [comment]
And here

**Comment by Slapbox** [comment]
@rastilho8 if you found a solution for this please share it - otherwise would you please re-open the issue?

**Comment by mr-ryan-james** [comment]
https://github.com/mmazzarolo/react-native-dialog/issues/95#issuecomment-802100610
